name: siakad_trivium
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0 
  # supabase_flutter: ^1.10.17
  http: ^1.2.1 # Atau versi terbaru
  shared_preferences: ^2.2.3 # Atau versi terbaru
  provider: ^6.1.2 # Atau versi terbaru

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # versi terbaru saat ini

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo/Logo.png" # path ke ikonmu

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo/Logo.png
    - lib/assets/images/avatar.jpg
    - lib/assets/images/news.png
    - lib/assets/ikon/boy.png
    - lib/assets/ikon/girl.png
    - lib/assets/ikon/chart.png
    - lib/assets/ikon/folder.png
    - lib/assets/ikon/calendar.png


